# GitHub PagesとJekyllについて - GitHub ヘルプ
# https://help.github.com/ja/github/working-with-github-pages/about-github-pages-and-jekyll

# Configuration | Jekyll • Simple, blog-aware, static sites
# https://jekyllrb.com/docs/configuration/


theme: jekyll-theme-minimal

title: "geeko.dev"
